contributors page added
gabrysia694/Gym-Junkies pull request #111
Opened 2023-05-03 11:05 UTC by Lalman888

contributors page added issue #44

2023-05-03 12:55 UTC, priyankarpal commented
hey, we can use GitHub API to fetch contributors' details. we don't need to do it manually. 
when a contributor's PR get merged, GitHub API automatically shows contributors. @Lalman888

2023-05-03 14:05 UTC, Lalman888 commented
@priyankarpal  okay I will add github api. Any other suggestion ?

2023-05-03 14:10 UTC, priyankarpal commented
> @priyankarpal okay I will add github api. Any other suggestion ?

sounds good

2023-05-03 14:30 UTC, priyankarpal commented
so looks good. 

But there is a problem when a user refreshes the page over `60` times in just an hour the contributor's list will not be shown to the user to increase the API limit we need to add authorization where we need to add our `GitHub personal token`.

If we use `GitHub Token` github API will give `1000` requests per hour I guess. it will be more helpful for us.

2023-05-03 14:33 UTC, Lalman888 commented
@priyankarpal you add that later

2023-05-03 14:34 UTC, priyankarpal commented
> @priyankarpal can you add that later

ok cool 

I will add that later.

2023-05-03 14:36 UTC, priyankarpal approved these changes
Looks Good 🎉

2023-05-04 16:50 UTC, gabrysia694 requested changes

2023-05-04 16:50 UTC, gabrysia694 commented on src/components/contributors/ContributorCard.jsx
> +          <h2 className="text-lg font-medium">{login}</h2>
When the dark theme is on, login disappears because it changes color to white which is the same as background. Could you add `className="text-black"`?

2023-05-04 17:51 UTC, Lalman888 commented on src/components/contributors/ContributorCard.jsx
> +          <h2 className="text-lg font-medium">{login}</h2>
@gabrysia694 Can you check now

2023-05-04 21:13 UTC, gabrysia694 approved these changes

2023-05-04 21:13 UTC, merged