Added Bulgarian Split Squats.
gabrysia694/Gym-Junkies pull request #115
Opened 2023-05-04 07:19 UTC by Pyth0nHere

Added a new exercise to the JSON file.

2023-05-04 16:14 UTC, gabrysia694 requested changes

2023-05-04 16:14 UTC, gabrysia694 commented on src/DB/exerciseData.json
>    }
Looks good but you're missing a comma here

2023-05-05 07:07 UTC, Pyth0nHere commented
RESOLVED!

2023-05-05 18:29 UTC, gabrysia694 approved these changes

2023-05-05 18:32 UTC, merged