Add a new exercise
gabrysia694/Gym-Junkies pull request #137
Opened 2023-05-08 16:56 UTC by MehmetTerc

2023-05-08 23:09 UTC, gabrysia694 requested changes
Please remove the last sentence of your instruction as it describes the effect of the exercise rather than providing a step on how to correctly perform the exercise.

2023-05-08 23:09 UTC, gabrysia694 commented on src/DB/exerciseData.json
> +    "Stand with feet shoulder-width apart, hinge at the hips while keeping a straight back,"
You're missing a comma here

2023-05-08 23:09 UTC, gabrysia694 commented on src/DB/exerciseData.json
> +    "lower the weight close to the body, and drive through the heels to return. Maintain a "
And one more comma here

2023-05-09 13:43 UTC, MehmetTerc commented
@gabrysia694 I correct my mistakes, can you merged it

2023-05-09 15:13 UTC, gabrysia694 requested changes

2023-05-09 15:13 UTC, gabrysia694 commented on src/DB/exerciseData.json
> +    "Stand with feet shoulder-width apart, hinge at the hips, while keeping a straight back,"
You're missing a comma right here, should be `"Stand with feet shoulder-width apart, hinge at the hips, while keeping a straight back,",`

2023-05-09 20:18 UTC, gabrysia694 approved these changes

2023-05-09 20:20 UTC, MehmetTerc commented
i correct the missing comma

2023-05-09 20:20 UTC, merged