added my favorite exercise
gabrysia694/Gym-Junkies pull request #141
Opened 2023-05-12 18:21 UTC by Kruthardh11

contributed by adding my favorite my exercise 'Hammer curls'.

2023-05-12 19:39 UTC, gabrysia694 requested changes
could you delete the `.history/src/DB` folder?

2023-05-13 04:35 UTC, Kruthardh11 commented
I deleted the the requested folder.

2023-05-14 10:11 UTC, Kruthardh11 commented
please, can I know the status of my PR.

2023-05-14 13:01 UTC, gabrysia694 approved these changes

2023-05-14 13:02 UTC, merged