New feature
gabrysia694/Gym-Junkies pull request #72
Opened 2023-04-22 23:48 UTC by benharrimohamed

2023-04-23 10:54 UTC, gabrysia694 requested changes
There's 18 exercises on the website at the moment, `<span className="text-indigo-600"> {jsonData.length} </span>` should fix the problem :)

2023-04-25 00:39 UTC, mshamir11 requested changes

2023-04-25 00:39 UTC, mshamir11 commented on package-lock.json
Why do we have to commit `package-lock.json` as the changes you have does not introduce any additional dependency. Please correct me if I'm wrong.

2023-04-25 18:31 UTC, gabrysia694 commented on package-lock.json
The `package.json` file was updated before merging this pull request, that's why `package-lock.json` file might have conflicts here because it was generated with the previous version of `package.json`. I don't know if that's what you were asking.

2023-04-26 01:40 UTC, mshamir11 commented on package-lock.json
The ```pr``` request had committed ```package-lock.json``` when the pr does not have any dependency changes. Ideally, we should rebase before committing and only include the changes we have for the issue. That's a best practice followed everywhere.

2023-04-30 16:26 UTC, closed without merging